### PR TITLE
Fix #223: Do not start session for Alert widget in case no session ID…

### LINKED ISSUE #223: Виджет Alert работает неверно
Дело в том, что он всегда стартует сессию. А это неверное поведение. Мое мнение, что не нужно запускать сессию, если на то нет явных причин.

На строке 52
https://github.com/yiisoft/yii2-app-basic/blob/master/widgets/Alert.php#L52

Требуется за место
```php
$session = Yii::$app->session;
```

Напиасть:

```php
$session = Yii::$app->session;
if (empty($session->getHasSessionId())) {
    return null;
}
```

Тогда все будет работать отлично!

### PR DESCRIPTION
**Pull request by samdark**
… was passed

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #223

### CODE REVIEW

**Comment by xepozz** [comment]
It may break BC. 
I think it can be configured via widget options with default value "autostart session enabled"

**Comment by viktorprogger** [comment]
Can't we implement this inside `getAllFlashes`?

**Comment by samdark** [comment]
@viktorprogger yeah, maybe.

**Comment by viktorprogger** [comment]
@samdark after some reflections I've decided it can lead to some BC because there will no longer be an initiated session where it was before. But I'm also not sure if it matters.

**Comment by samdark** [comment]
Yes. It is tricky...

**Pull request closed without merging**
