### PR TITLE
Set en language in test

### PR DESCRIPTION
**Pull request by githubjeka**
When I change language to `ru` then `my` tests works, but Yii tests doesn't works.

To corrects this behavior added in test config
```
'language' => 'en-US',
```

### CODE REVIEW

**Comment by cebe** [comment]
can you show how the tests fail?

**Comment by githubjeka** [comment]
```
codecept run acceptance acceptance\LoginCept.php
Codeception PHP Testing Framework v2.0.12
Powered by PHPUnit 4.5.1 by Sebastian Bergmann and contributors.

Tests\codeception\backend.acceptance Tests (1) -----------------------------------------------------------------------------------------------
Trying to ensure login page works (D:/projects/yii2-tutorial/yii2-app-advanced/tests/codeception/backend/acceptEnsure login page works (D:/projects/yii2-tutorial/yii2-app-advanced/tests/codeception/backend/acceptance/LoginCept)                    Fail
----------------------------------------------------------------------------------------------------------------------------------------------


Time: 612 ms, Memory: 16.00Mb

There was 1 failure:

---------
1) Failed to ensure login page works in D:/projects/yii2-tutorial/yii2-app-advanced/tests/codeception/backend/acceptance/LoginCept (D:\projects\yii2-tutorial\yii2-app-advanced\tests\codeception\backend/acceptance\LoginCept.php)
Couldn't see "Username cannot be blank.",".help-block":
Failed asserting that any element by '.help-block' on page /yii2-app-advanced/backend/web/index-test.php?r=site%2Flogin
+ <p class="help-block help-block-error">╨Э╨╡╨╛╨▒╤Е╨╛╨┤╨╕╨╝╨╛ ╨╖╨░╨┐╨╛╨╗╨╜╨╕╤В╤М ┬лUsername┬╗.</p>
+ <p class="help-block help-block-error">╨Э╨╡╨╛╨▒╤Е╨╛╨┤╨╕╨╝╨╛ ╨╖╨░╨┐╨╛╨╗╨╜╨╕╤В╤М ┬лPassword┬╗.</p>
+ <p class="help-block help-block-error"></p>
contains text 'Username cannot be blank.'

Scenario Steps:
7. I see "Username cannot be blank.",".help-block"
6. I expect to see validations errors
5. I click "login-button"
4. I fill field "input[name="LoginForm[password]"]",""
3. I fill field "input[name="LoginForm[username]"]",""
2. I am going to submit login form with no data
1. I am on page "/backend/web/index-test.php?r=site%2Flogin"


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

**Comment by cebe** [comment]
Thanks!

**Comment by githubjeka** [comment]
Do you PR self for advanced app?

**Comment by cebe** [comment]
would be great if you could add it

**Pull request merged**
