### PR TITLE
Create a .gitkeep file inside test data directory

### PR DESCRIPTION
**Pull request by Kolyunya**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

1. What is the point of ignoring everything inside `_data`?
2. I believe `.gitkeep` is more semantic, meaning that it's here holding a place for your data.

### CODE REVIEW

**Comment by samdark** [comment]
Isn't `_data` contains what's generated automatically?

**Comment by Kolyunya** [comment]
I don't think [so](https://github.com/yiisoft/yii2-app-advanced/tree/master/common/tests/_data).

**Comment by samdark** [comment]
OK. Merged. Thank you!

**Comment by Kolyunya** [comment]
My pleasure!

**Pull request merged**
