### PR TITLE
Dependencies should be stable

### PR DESCRIPTION
**Pull request by DavertMik**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | should pass :)
| Fixed issues  | no

Installation goes smoothly and fast:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing yiisoft/yii2-composer (2.0.4)               
    Downloading: 100%         

  - Installing swiftmailer/swiftmailer (v5.4.3)
    Downloading: 100%         

  - Installing bower-asset/jquery (2.2.4)
    Downloading: 100%         

  - Installing bower-asset/yii2-pjax (v2.0.6)
    Downloading: 100%         

  - Installing bower-asset/punycode (v1.3.2)
    Downloading: 100%         

  - Installing bower-asset/jquery.inputmask (3.2.7)
    Downloading: 100%         

  - Installing cebe/markdown (1.1.0)
    Downloading: 100%         

  - Installing ezyang/htmlpurifier (v4.7.0)
    Loading from cache

  - Installing yiisoft/yii2 (2.0.9)
    Downloading: 100%         

  - Installing yiisoft/yii2-swiftmailer (2.0.5)
    Downloading: 100%         

  - Installing yiisoft/yii2-codeception (2.0.5)
    Downloading: 100%         

  - Installing bower-asset/bootstrap (v3.3.5)
    Downloading: 100%         

  - Installing yiisoft/yii2-bootstrap (2.0.6)
    Downloading: 100%         

  - Installing yiisoft/yii2-debug (2.0.6)
    Downloading: 100%         

  - Installing bower-asset/typeahead.js (v0.11.1)
    Downloading: 100%         

  - Installing phpspec/php-diff (v1.1.0)
    Downloading: 100%         

  - Installing yiisoft/yii2-gii (2.0.5)
    Downloading: 100%         

  - Installing fzaninotto/faker (v1.6.0)
    Loading from cache

  - Installing yiisoft/yii2-faker (2.0.3)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

Much better than clonong all master branches =)

### CODE REVIEW

**Comment by samdark** [comment]
@yiisoft/core-developers I think we should change it.

**Comment by klimov-paul** [comment]
With such change there is no way to get package, which has no stable release yet or just `dev-master`.

**Comment by DavertMik** [comment]
@klimov-paul actually there is way. You can set `@dev-master` in deps and get all the latest dependencies if you wish. But hey, it is 2016! Everyone should have at least 0.0.x release today.

**Comment by samdark** [comment]
@klimov-paul all our packages are released except queues which are in the works and should not be used yet so it should not be a problem. That's a template for *new* projects and won't affect existing ones.

**Comment by klimov-paul** [comment]
I usually use `minimum-stability: dev` and `prefer-stable` for the project:
https://github.com/yii2tech/project-template/blob/master/composer.json#L20-L21

This allows me to split repo into several ones, developing extensions in parallel with the project itself.

Still for `yii2-app-basic` it may be fine to require stable version by default. I have nothing against the change.

**Comment by cebe** [comment]
the stable version of relased packages always has the stable requirement, if you use the dev version, you get a dev requirement. 

See https://github.com/yiisoft/yii2-app-basic/commit/5319c23281f4543da41f7f5ed72837f597fe9ab4 and https://github.com/yiisoft/yii2-app-basic/commit/548af0eacdd8d000bde121b122d0f36e2c218605

**Comment by samdark** [comment]
Ah. Good.

**Pull request closed without merging**
