### PR TITLE
Use PHP_EOL instead of ”\n“ for windows CLI output

### PR DESCRIPTION
**Pull request by duruitang**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| Is enhancement?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | no

### CODE REVIEW

**Comment by samdark** [comment]
Why?

**Comment by duruitang** [comment]
see http://stackoverflow.com/questions/1761051/difference-between-n-and-r

**Comment by cebe** [comment]
I know the difference but does this really cause any issues on windows? We use `\n` in all other console commands in the framework. I have no windows system to test this myself but I have not seen any complaint so far.

**Comment by samdark** [comment]
I have Windows and haven't experienced any issues with using `\n`.

**Comment by duruitang** [comment]
I got this problem before(win7, China, php5.4), but just once. It's weird. So I think PHP_EOL is more reliable.

**Comment by samdark** [comment]
What do you mean by "this" problem?

**Comment by duruitang** [comment]
Sorry, It looks like this:
```
foreach (['a', 'b', 'c'] as $v) {
    echo "$v \n";
}

echo "\r\n";

foreach (['a', 'b', 'c'] as $v) {
    echo "$v \r\n";
}
```
output
```
a b c 
a
b
c
```

**Comment by samdark** [comment]
Do you use standard `cmd`?

**Comment by samdark** [comment]
Which Windows version is that?

**Comment by duruitang** [comment]
`standard cmd` or `nodejs cmd`, I forgot which `cmd` I used. .
Windows version: Windows 7 Home Basic

**Comment by samdark** [comment]
Checked Windows 10 with cmd, PowerShell and git bash. Works well with just `\n`. Not sure what "nodejs cmd" is.

**Comment by samdark** [comment]
Closing till there's a reproducible way to confirm it.

**Pull request closed without merging**
