### PR TITLE
Fixed Selenium running command

### PR DESCRIPTION
**Pull request by ElisDN**
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Tests pass? | yes |
| Fixed issues |  |

### CODE REVIEW

**Comment by samdark** [comment]
Won't accept the change. It's specific for Gecko-based browsers and your environment.

**Comment by ElisDN** [comment]
Hm... It is nessesary for default `browser: firefox` configuration from `acceptance.sute.yml.example`.

**Comment by DavertMik** [comment]
@ElisDN firefox can be started with either older version or from docker container. In both option there is no need for Ghecko driver. 

Can you update documentation to specify exactly the Ghecko / Chrome options for selenium to execute. Thanks

**Comment by DavertMik** [comment]
@ElisDN to be honest that is very helpful advice. But could you write a bit more about Gecko driver how to install it and probably suggest docker as an alternative. I always do it like:

```
docker run --net=host selenium/standalone-firefox:2.53.0
```

and then I have headless Firefox + Selenium

**Comment by cebe** [comment]
what is the state of this pull request? @ElisDN are you willing to adjust it?

**Comment by ElisDN** [comment]
@cebe Updated commit and rebased branch.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
