### PR TITLE
Removed Swiftmailer dependency

### PR DESCRIPTION
**Pull request by luke-**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/Codeception/module-yii2/issues/64

### CODE REVIEW

**Comment by bizley** [comment]
I guess so. Please confirm, @samdark

**Comment by SamMousa** [comment]
You've replaced it with a new hidden dependency though. Can't we just have a trivial value object implementation of the message interface and use that?

**Comment by developedsoftware** [comment]
> You've replaced it with a new hidden dependency though. Can't we just have a trivial value object implementation of the message interface and use that?

Whilst much better, surely just removing swiftmailer is a step forward?

**Comment by luke-** [comment]
Ok, yes it is still a hidden dependency. This is about removing the deprecated SwiftMailer dependency for the tests only.

**Comment by developedsoftware** [comment]
Can this be merged @samdark

**Pull request merged**
