### PR TITLE
Move YII_ENV in console and web to env config file

### PR DESCRIPTION
**Pull request by margori**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | none

I moved YII_ENV and YII_DEBUG directives to a single file in config folder so those configuration values are available and consistent in console command, migrations and web site.

### CODE REVIEW

**Comment by samdark** [comment]
I don't personally think that these should be shared like that. Console is technically a separate application...

**Comment by margori** [comment]
> I don't personally think that these should be shared like that.
Great. I invite you to suggest a better idea.
> Console is technically a separate application...
I see site and console separate too, but we need to coordinate them, that's why a propose a single directive to set the state of whole project.

**Comment by samdark** [comment]
A better idea is in advanced project template with `init` command and environments...

**Comment by samdark** [comment]
Won't accept this change. Sorry.

**Comment by margori** [comment]
No problem. :) Just sharing.

**Pull request closed without merging**
