### PR TITLE
move db config to .env

### PR DESCRIPTION
**Pull request by songlipeng2003**

### CODE REVIEW

**Comment by pana1990** [comment]
what does it happen with tests enviroment?
why do you include .env in cvs?

i have developed this feautre in my template, can you check here : 

 https://github.com/pana1990/yii2-app (it is under development)

**Comment by samdark** [comment]
Won't accept that. Sorry.

**Comment by songlipeng2003** [comment]
why? I think that move all config to .env is better like laravel

**Comment by cebe** [comment]
for more advanced configuration handling, see https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/structure-environments.md

**Comment by songlipeng2003** [comment]
@cebe thanks

**Comment by evalenzuela** [comment]
@samdark @cebe One of problems with *-local.php files that is easy to forget to upload/deploy them (We had that issue)...There's a chance to integrate the following package?

[phpdotenv](https://github.com/vlucas/phpdotenv)

I integrate it in every project I do with Yii2 (it's very boring do it very often, or not?).

.env files is a good starting point (like other PHP frameworks and Node.js frameworks)

**Comment by zorobabel** [comment]
@samdark @cebe One of problems with *-local.php files that is easy to forget to upload/deploy them (We had that issue)...There's a chance to integrate the following package?

phpdotenv

I integrate it in every project I do with Yii2 (it's very boring do it very often, or not?).

.env files is a good starting point (like other PHP frameworks and Node.js frameworks)

**Comment by samdark** [comment]
If you're using it w/ each project and you have many projects, it's a good idea to create your own project template. phpdotenv has issues with env files in mpm-apache based deployments so I'd not recommend it as default option. May cause serious issues.

**Comment by zorobabel** [comment]
@samdark oh, good point

**Pull request closed without merging**
