### PR TITLE
Bump codeception/specify, codeception/verify versions

### LINKED ISSUE #172: test [Error] Class 'PHPUnit_Framework_Assert' not found
When I run `./vendor/bin/codecept run` ,
There are many errors for unit test,likely '[Error] Class 'PHPUnit_Framework_Assert' not found'

Just because the  'codeception/verify' version is too old:
```
"require-dev": {
         //...  
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
```
PHPUnit_Framework_Assert is replace by PHPUnit\Framework\Assert
```
"require-dev": {
         //...  
        "codeception/verify": "~1.0.0",
        "codeception/specify": "~0.4.6"
    },
```
**Pls NOTE: Maybe codeception/specify composer.json has an error. So cannot update to v1.0.**
So you can upgrade the composer.json
Thanks.

### PR DESCRIPTION
**Pull request by ricpelo**
Close #172.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #172

### CODE REVIEW

**Comment by ricpelo** [comment]
Travis-CI fails for PHP 5.4 due to bug Codeception/Codeception#4836.

**Comment by schmunk42** [comment]
Would it work with Codeception 2.3?

**Comment by samdark** [comment]
codeception/specify constraint was OK. It would install new version specified.

If answer to @schmunk42 question is no then codeception/verify could be specified as `~0.3.1|~0.4.0`.

**Comment by ricpelo** [comment]
@schmunk42 Yes, it seems to be OK for PHP 5.4 with Codeception 2.3.

**Comment by matjack1** [comment]
Just to give a feedback, this works fine here too :)

I would give my :+1: in merging this.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
