### PR TITLE
Fix #56: configure Codeception::Scpecify to not deep clone properties by default 

### LINKED ISSUE #56: Codeception specify causes Maximum function nesting level error
### What steps will reproduce the problem?
Runing unit tests examples cause errors ```Maximum function nesting level``` the first test works fine but others dont work
### Additional info
It seems that ```Codeception\Specify\Config``` have ```setDeepClone``` property that can be set to ```false``` and all tests pass after puting that
### more details 
https://github.com/Codeception/Specify/blob/master/docs/GlobalConfig.md

### PR DESCRIPTION
**Pull request by cherifGsoul**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #56

### CODE REVIEW

**Comment by cherifGsoul** [comment]
@cebe Im confused, you are refering the PR as a bug you mean it has as bug or it corrects a bug?

**Comment by cebe** [comment]
labeling as bug means that it fixes a bug. it is just for us internally to manage issues better. bugs have slightly higher priority for merging and reviewing than features.

**Comment by cherifGsoul** [comment]
thank you :)

**Comment by cebe** [comment]
Merged, thank you!

**Comment by cherifGsoul** [comment]
Thanks :)

**Comment by Naktibalda** [comment]
This change made Codeception's --prefer-lowest builds fail.
Codeception/Specify is an indirect dependency, please add it to require-dev section in composer.json

**Pull request merged**
